### ISSUE TITLE
Nedoplňují se tel. čísla v seznamu kynologů

### ISSUE THREAD

**Issue by vmakes** [ruz76/qgis_patrac_3#116]
Telefonní čísla v seznamu dostupných a zařazených kynologů se doplňují pouze u členů HS u ostatních chybí.

**Comment by ruz76** [comment]
Vypadá to, že nejsou přiřazena na straně HS.

**Comment by ruz76** [comment]
Jirka Doplnil čísla. Už se zobrazují.
