### ISSUE TITLE
Stav psovoda v seznamech se neaktualizuje

### ISSUE THREAD

**Issue by vmakes** [ruz76/qgis_patrac_3#118]
Stav psovoda uveden v seznamech dostupných a zařazených psovodů se nemění dle aktuálního stavu.

**Comment by vmakes** [comment]
Po vyžádání psovoda, tento stav se změní z Dostupný na Neřeší a stav neřeší tam již zůstane stále i když psovod výzvu přime (potvrdí tlačítkem řeším).

Jinak potvrzuji, že telefonní čísla psovodů se již do seznamu propisují.

Vláďa

**Comment by ruz76** [comment]
Tak to je. Toho jsem si všiml. Podle mně SIMOPT změnil trochu API. Já jsem to nějak opravil, tedy zobrazí se Řeší, ale nevím jestli to je systémově dobře. To chci ještě probrat se SIMOPT.

Aktuální stav:
if user["vyzvaPotvrzena"]:
                        # TODO consult this with SIMOPT - does not seem to be stable behaviour
                        user_from_calls["state"] = self.tr("Accepted")
                        self.setUserFromCallsState(user, self.tr("Accepted"))
                        # if "lastReactionType" in user and user["lastReactionType"] == "accepted":
                        #     user_from_calls["state"] = self.tr("Accepted")
                        #     self.setUserFromCallsState(user, self.tr("Accepted"))
                        # else:
                        #     user_from_calls["state"] = self.tr("Not accepted")
                        #     self.setUserFromCallsState(user, self.tr("Not accepted"))

**Comment by ruz76** [comment]
Issue uzavírám. Zatím se zdá, že to funguje i v této kombinaci. Dotaz na SIMOPT jsem poslal.
