### ISSUE TITLE
Strukturování záznamů prošlých tras

### ISSUE THREAD

**Issue by vmakes** [ruz76/qgis_patrac_3#47]
Importované prošlé trasy je potřeba rozdělovat podle jednotlivých záznamů (zařízení, prací), jak on-line tak off-line. Dále by bylo vhodné je automaticky zařadit do své speciální složky v požadované vrstvě. Dále by bylo velmi vhodné jednotlivým zařízením automaticky přidělovat různou barvu tracku.

**Comment by ruz76** [comment]
Barva může být problém.

**Comment by ruz76** [comment]
Barvy zatím necháme být. To je složité. nechal bych na uživateli, pokud má zájem.

**Comment by ruz76** [comment]
Zařazování implementováno.
