### ISSUE TITLE
Rozlišení testování - ostré akce

### ISSUE THREAD

**Issue by vmakes** [ruz76/qgis_patrac_3#49]
Do prvního kroku zařadit zaškrtávací pole zda se jedná o ostrou nebo zkušební akci. Data ze zkušební akce neukládat. U dat pro využití k predikci výskytu PO a k rychlostem pátracích prostředků vyřešit systém verifikace od odpovědných a náležitě poučených osob. Za každé KŘP jeden až dva.

**Comment by ruz76** [comment]
U dat pro využití k predikci výskytu PO a k rychlostem pátracích prostředků vyřešit systém verifikace od odpovědných a náležitě poučených osob. Za každé KŘP jeden až dva. - Nové issue.
