### ISSUE TITLE
Mobilní svolávací systém pro Atestované kynology

### ISSUE THREAD

**Issue by vmakes** [ruz76/qgis_patrac_3#50]
Před nasazením do ostrého provozu vyřešit:
1. Zjednodušit zadávání stavu kynologa pouze "Pohotovost", "Akce" a "Nedostupný"
2. Při vyžádání kynologů:
  - možnost výběru jednotlivých kynologů k oslovení
  - odeslání informací jméno kontaktní osoby, telefon, místo srazu (klik do mapy - souřadnice), popis pohřešované osoby
  - potvrzené výzvy kynologem logickými tlačítky "přijmout" a "odmítnout" (později přidat možnost "mohu přijet za 1 až 5 h.)
  - zpětná informace do SW Pátrač o stavu kynologa (zda přijal či zda odmítl)
  - automatické odeslání informace na KOPIS HZS a PČR o vyžádání kynologů: název akce, velitel akce, seznam kynologů, čas)
  - po potvrzení přijetí výzvy automatické přepnutí do stavu "Akce"
  - Postupné (následné) vyzvání dalších psovodů
  - zrušení výzvy (odvolání akce) opět s alarmem

**Comment by vmakes** [comment]
Přehodnocení funkcionality psovod mohu přijet za xy
tlačítka přijmout a odmítnout (požadavek HS byl právě na řeším - nutno domluvit společnš)

**Comment by ruz76** [comment]
V zásadě implementováno. Po přehodnocení kdyžtak založit nové issue, pokud něco chybí.
