### ISSUE TITLE
Report - map

### ISSUE THREAD

**Issue by vmakes** [ruz76/qgis_patrac_3#51]
Do reportu sestavy celého území nastavit implicitní měřitko 1:25000

**Comment by vmakes** [comment]
Do přehledu sektorů doplnit informaci o mapovém listě (z přednastavené sestavy)

**Comment by ruz76** [comment]
Přehled sektorů udělán jako nové issue.

**Comment by ruz76** [comment]
Implicitní měřítko 1:25 000 může být, ale může to způsobit že bude více listů této přehledové mapy. Což asi nevadí. V mapě by dle kluků z Plzně měly být popisky sektorů, do 1:25000 by se vlézt měly, asi je ještě zmenšíme na 8pt.
