### ISSUE TITLE
Zobrazení hranic sektorů

### ISSUE THREAD

**Issue by vmakes** [ruz76/qgis_patrac_3#53]
Je možnost zobrazit (hlavně pro tisk) hranice sektorů průsvitnou barvou, tak aby barva neskrývala detaily na mapě?

**Comment by ruz76** [comment]
To by neměl být problém.

**Comment by vmakes** [comment]
Při testech se jeví jako nejvhodnější pro tisk červená průhledná na 20%. Mám zatím problém s tím, že tam kde jsou přes sebe dvě čáry je průhlednost hned poloviční.

**Comment by ruz76** [comment]
Mohli bychom vyřešit tím, že pro tisk uděláme jen jednu čáru. To by mělo jít.

**Comment by ruz76** [comment]
Nakonec zatím použit následující styl, přičemž necháme čáty přes sebe. Časem možná vyešíme i to překrytí.

<prop v="255,1,255,38" k="outline_color"/>
<prop v="solid" k="outline_style"/>
<prop v="1.0" k="outline_width"/>
