### ISSUE TITLE
UTM

### ISSUE THREAD

**Issue by vmakes** [ruz76/qgis_patrac_3#54]
Je možné, aby se mohla nastavit pro tisk libovolná hustota mřížky UTM? Je pro Tebe řešitelné dostat mřížku UTM do navigačních přístrojů (Garmin, mobilní telefony)?

**Comment by ruz76** [comment]
Hustota mřížky se dá nastavitručně. Pokud by to mělo být automaticky, pak musí být někde pole (list), před vygenerováním map, kde uživatel zvolí nějaké parametry. Možná by tam na posledním kroku molo být tlačítko nastavení, kde by si uživatel zvolil nějaké parametry: hustotu mřížky, zobrazit popisky sektorů vždy, měřítko přehledové mapy.
