### ISSUE TITLE
Chyby v sektorech

### ISSUE THREAD

**Issue by vmakes** [ruz76/qgis_patrac_3#68]
Například sektory JM207 a JM220 v Pak v sobě obsahují různé druhy povrchů (až 4 druhy - pole, louka, les, cesta).

**Comment by ruz76** [comment]
Nejedná se přímo o bug. Jde o to, že vektor neodpovídá úplně přesně rastru. Ty typy povrchů mimo hlavní jsou minoritní. Taky se může jednat např. o budovy v lese nebo malé vodní plochy. Malé plochy do 500 m2 nejsou jako samostatné sektory, ale jsou připojeny k některému většímu sektoru.
