### ISSUE TITLE
Tisky neodpovídají udávanému měřítku

### ISSUE THREAD

**Issue by vmakes** [ruz76/qgis_patrac_3#69]
Nastavený tisk 1:100000 je v reálu skoro 1:20000!

**Comment by ruz76** [comment]
Dočasně fixnuto pomocí průměrné konstanty pro celou ČR. Na okrajích by mělo dělat chybu max 10 m na 1 km. Verze QGIS 3.16 by měla toto řešit.

**Comment by ruz76** [comment]
Grafické měřítko je v pořádku. Číselůné musel být dočasně odstraněno.
