### ISSUE TITLE
Nastavení tření

### ISSUE THREAD

**Issue by vmakes** [ruz76/qgis_patrac_3#71]
Bylo by možné nastavovat uživatelsky tření v nastavení? Včetně limitu sklonu pro neprostupnost.

**Comment by ruz76** [comment]
Šlo by to, ale nevidím moc užitečnost globálně. Tady by to chtělo širší diskusi v rámci pracovní skupiny.

**Comment by vmakes** [comment]
Souhlas s globální užitečností. Ptám se jak by to bylo složité pro Tebe nastavit, abych tuto funkci měl chvíli k dispozici, nebo zda bych to mohl někde (ne moc složitě) zkušebně upravovat pro potřebu testování. Mám v úmyslu projet všechny naše pátračky z posledních deset let co máme dobře zdokumentované a porovnat výstupy různých nastavení se skutečností v terénu a logikou pohybu té osoby.

**Comment by ruz76** [comment]
Složité to není. Odhad tak 2 hodiny práce. Jen si nejsme jistý jak tam jě teď řešen ten sklon svahu, zda jsem to úplně nezrušil a tedy podmínka 45 stupňů už neplatí a vše se bere z r.walk. Podobných issues je více. Já bych teď rád dokončil všechny co si myslím, že budou potřeba primárně a pak bych ti poslal seznam těch co zbydou s odhadem doby na realizaci. Ty by jsi pak stanovil priority. Poslal bych to zítra.
